Task 2
katya-sanko/react_spa pull request #2
Opened 2018-04-26 21:48 UTC by katya-sanko

2018-04-27 08:42 UTC, EduardTrutsyk requested changes
server - имеется ввиду `web serve`, который будет запускать вебпак, отдавать статические файлы. Не нужно писать `api server`, в качестве апи, вы будете использовать сторонний api server.
Web server Должен быть на express, в дев моде нужно подлючить [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware) и для hot reload [webpack-hot-middleware](https://github.com/webpack-contrib/webpack-hot-middleware)
Запускать этот сервер должен командой `npm start` в зависимости от NODE_ENV в `production` или `development` моде.

2018-04-27 08:42 UTC, EduardTrutsyk commented on client/package.json
>    "name": "client",
лучше сделать что бы был один `package.json`

2018-04-27 08:42 UTC, EduardTrutsyk commented on client/webpack.common.js
> +                exclude: /(node_modules|bower_components)/,
Ты используешь `bower_components` ?

2018-04-27 08:42 UTC, EduardTrutsyk commented on client/webpack.common.js
> +                        presets: ['env']
Не нужно дублировать бабел опции тут и в `.babelrc` Достаточно в файле `.babelrc`

2018-04-27 08:55 UTC, EduardTrutsyk requested changes
также каждый компонент должен быть в отдельном файле, а еще лучше паке где будет лежать компонет, стили к нему и тесты :)

2018-04-27 08:55 UTC, EduardTrutsyk commented on README.md
> +  - run node server: `npm run start`
очень круто что есть `README.md` только не забывай обновлять когда изменяются команды

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/package.json
> +    "serve:dev": "webpack-dev-server --port 3002 --config webpack.dev.js",
нельзя использовать `webpack-dev-server`

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/package.json
> +    "build:prod": "webpack --config webpack.prod.js"
тут нехвататет `NODE_ENV=production`, так как эта команда явно для prod. можно использовать [cross-env](https://github.com/kentcdodds/cross-env)

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/src/index.js
> +// import './style.css';
это тут действительно нужно?

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/src/index.js
>  //     <h1>Hello, world!</h1>,
и это?

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/webpack.common.js
> +            // {
думаю такие комментарии можно  удалить

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/webpack.dev.js
> +            'process.env.NODE_ENV': JSON.stringify('production')
в dev конфиге `production`?

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/webpack.prod.js
> +            sourceMap: true
`sourceMap` в продакшене не нужны, + это ускорит билд

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/webpack.prod.js
> +            'process.env.NODE_ENV': JSON.stringify('production')
по хорошему это можно перенести в `common` норфиг и устанавливать значение из `NODE_ENV` ;)

2018-04-27 08:55 UTC, EduardTrutsyk commented on client/webpack.dev.js
> +            "/greeting": "http://localhost:3001"
я думаю это никогда не понадобится

2018-04-27 09:07 UTC, EduardTrutsyk requested changes

2018-04-27 09:07 UTC, EduardTrutsyk commented on client/webpack.dev.js
> +            'process.env.NODE_ENV': JSON.stringify('production')
еще в дев моде было бы хорошо настроить hot reload: [hot-module-replacement](https://webpack.js.org/guides/hot-module-replacement/)

2018-05-01 22:02 UTC, katya-sanko commented on client/webpack.common.js
> +                        presets: ['env']
спасибо большое за комменты! (я только сейчас заметила, нотификашки не пришли =\) завтра просмотрю и поправлю.

2018-05-09 12:26 UTC, merged